### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by arayate** [jarrekk/imgkit#10]
`image = from_url(preview_url, output_path=image_path)`

Gives below error:

```
wkhtmltoimage exited with non-zero code -6. error:
QXcbConnection: Could not connect to display
```

Environment: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by jarrekk** [comment]
This may because you are using this library at a headless server, there is a [solution](https://unix.stackexchange.com/questions/192642/wkhtmltopdf-qxcbconnection-could-not-connect-to-display) of this bug of **wkhtmltopdf**, could you show me more stderr of this? later I will fix it at this library. thanks!

**Comment by arayate** [comment]
Pasting the relevant partial stack trace. 

```
/imgkit/imgkit.py", line 230, in to_img
    raise IOError("wkhtmltoimage exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
OSError: wkhtmltoimage exited with non-zero code -6. error:
QXcbConnection: Could not connect to display
```

**Comment by arayate** [comment]
Created a pull request, https://github.com/jarrekk/imgkit/pull/11

Please review.

**Comment by jarrekk** [comment]
With your PR, I add xvfb check in v0.1.4. To use it you should define options as `{'xvfb': ''}`

Thanks!
